### ISSUE TITLE
Add a few words about building it and the rationale to combine go and rust within a single project

### ISSUE THREAD

**Issue by KOLANICH** [bazelbuild/sandboxfs#118]

**Comment by jmmv** [comment]
The installation instructions are in the `INSTALL.md` file. What do you think is missing from those?

As to why this project contains Go and Rust code... it's only because of historical reasons. The first versions of sandboxfs were written in Go, and when I rewrote the code in Rust, I kept the same tests to ensure both versions behaved identically. The tests could now (and should be) rewritten in Rust, but it's a large amount of work.

**Comment by KOLANICH** [comment]
Thanks for the info. It was just `INSTALL.md` filename a bit unexpected (it is the first project I have encountered where building information is within file which name assummes installation, nit building).

BTW, I don't recommend `cargo install`, there are some tools that would generate a package installable with a package manager, like `cargo deb`.
