### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by anp** [bazelbuild/sandboxfs#77]
Hi! Please forgive a rather uninformed question. Is support for Windows possible? Is it in scope?

**Comment by jmmv** [comment]
If Windows supported FUSE, it'd be. I see there are at least two projects that add such support, but I'm not sure what state they are in nor how fast they are.

Are you asking because of Bazel? If so, we need to add sandboxing support to Bazel *first*, and only then see if a sandboxfs-like solution would help at all.

**Comment by anp** [comment]
Thanks! I’m curious about its use for cargo buildscripts right now.
